model:
  type: wresnet28_10
dataset: cifar10
aug: randaugment
randaug:
  N: 3
  M: 5    # from appendix
cutout: 16
batch: 256
epoch: 200
lr: 0.1
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 2
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005